### ISSUE TITLE
App crashes when saving

### ISSUE THREAD

**Issue by Fauzdar1** [zacharee/FabricateOverlay#12]
Version 1.0.2 crashes when setting Navbar height to 1 and saving with/without entering any overlay name . 

Version 1.0.3-fix crashes or goes into not responding mode when searching.

Device - Realme 9 Pro+ 5G
Android version - 12

**Comment by DhruvaSharma** [comment]
App crashes right when saving overlay after entering name on version 1.1.0.
Device: Nothing Phone 1.

**Comment by PureWarden** [comment]
> App crashes right when saving overlay after entering name on version 1.1.0. Device: Nothing Phone 1.

Same issue here. This may helps :

``java
2022-08-19 10:53:02.858 31957-31957/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: tk.zwander.fabricateoverlay, PID: 31957
    java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at tk.zwander.fabricateoverlay.OverlayAPI.commit(OverlayAPI.kt:415)
        at tk.zwander.fabricateoverlay.OverlayAPI.registerFabricatedOverlay(OverlayAPI.kt:207)
        at tk.zwander.fabricateoverlaysample.ui.elements.dialogs.SaveOverlayDialogKt$SaveOverlayDialog$1$1$1$1.invoke(SaveOverlayDialog.kt:65)
        at tk.zwander.fabricateoverlaysample.ui.elements.dialogs.SaveOverlayDialogKt$SaveOverlayDialog$1$1$1$1.invoke(SaveOverlayDialog.kt:64)
        at tk.zwander.fabricateoverlay.OverlayAPI$Companion.getInstance(OverlayAPI.kt:100)
        at tk.zwander.fabricateoverlaysample.ui.elements.dialogs.SaveOverlayDialogKt$SaveOverlayDialog$1$1$1.invoke(SaveOverlayDialog.kt:64)
        at tk.zwander.fabricateoverlaysample.ui.elements.dialogs.SaveOverlayDialogKt$SaveOverlayDialog$1$1$1.invoke(SaveOverlayDialog.kt:62)
        at androidx.compose.foundation.ClickableKt$clickable$4$gesture$1$2.invoke-k-4lQ0M(Clickable.kt:137)
        at androidx.compose.foundation.ClickableKt$clickable$4$gesture$1$2.invoke(Clickable.kt:131)
        at androidx.compose.foundation.gestures.TapGestureDetectorKt$detectTapAndPress$2$1$1.invokeSuspend(TapGestureDetector.kt:223)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:178)
        at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:166)
        at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:397)
        at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:431)
        at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:420)
        at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:328)
        at androidx.compose.ui.input.pointer.SuspendingPointerInputFilter$PointerEventHandlerCoroutine.offerPointerEvent(SuspendingPointerInputFilter.kt:511)
        at androidx.compose.ui.input.pointer.SuspendingPointerInputFilter.dispatchPointerEvent(SuspendingPointerInputFilter.kt:407)
        at androidx.compose.ui.input.pointer.SuspendingPointerInputFilter.onPointerEvent-H0pRuoY(SuspendingPointerInputFilter.kt:420)
        at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:284)
        at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:271)
        at androidx.compose.ui.input.pointer.NodeParent.dispatchMainEventPass(HitPathTracker.kt:151)
        at androidx.compose.ui.input.pointer.HitPathTracker.dispatchChanges(HitPathTracker.kt:88)
        at androidx.compose.ui.input.pointer.PointerInputEventProcessor.process-BIzXfog(PointerInputEventProcessor.kt:80)
        at androidx.compose.ui.platform.AndroidComposeView.handleMotionEvent-8iAsVTc(AndroidComposeView.android.kt:965)
        at androidx.compose.ui.platform.AndroidComposeView.dispatchTouchEvent(AndroidComposeView.android.kt:938)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
        at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:504)
        at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1892)
        at android.app.Dialog.dispatchTouchEvent(Dialog.java:864)
        at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:462)
        at android.view.View.dispatchPointerEvent(View.java:14800)
2022-08-19 10:53:02.859 31957-31957/? E/AndroidRuntime:     at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6401)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6202)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5680)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5737)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5703)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5868)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5711)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5925)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5684)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5737)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5703)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5711)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5684)
        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:8623)
        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8574)
        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:8542)
        at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:8758)
        at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:260)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:335)
        at android.os.Looper.loopOnce(Looper.java:161)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7941)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1009)
     Caused by: java.lang.SecurityException: commit failed
        at android.os.Parcel.createExceptionOrNull(Parcel.java:2425)
        at android.os.Parcel.createException(Parcel.java:2409)
        at android.os.Parcel.readException(Parcel.java:2392)
        at android.os.Parcel.readException(Parcel.java:2334)
        at android.content.om.IOverlayManager$Stub$Proxy.commit(IOverlayManager.java:971)
        	... 67 more
     Caused by: android.os.RemoteException: Remote stack trace:
        at com.android.server.om.OverlayManagerService$1.commit(OverlayManagerService.java:877)
        at android.content.om.IOverlayManager$Stub.onTransact(IOverlayManager.java:485)
        at android.os.Binder.execTransactInternal(Binder.java:1179)
        at android.os.Binder.execTransact(Binder.java:1143)
2022-08-19 10:53:02.863 1673-676/? I/DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
2022-08-19 10:53:02.864 1673-2660/? W/ActivityTaskManager:   Force finishing activity tk.zwander.fabricateoverlay/tk.zwander.fabricateoverlaysample.MainActivity
2022-08-19 10:53:02.874 1515-1515/? E/CRASHALOG: event[wd:1,mask:0x80,cookie:82165,len:48,name:data_app_crash@1660899182869.txt]
2022-08-19 10:53:02.875 1515-1515/? E/CRASHALOG: get_only_save_trace_state false
`
`

**Comment by chincheang** [comment]
> App crashes right when saving overlay after entering name on version 1.1.0.
> Device: Nothing Phone 1.

Same here

**Comment by DhruvaSharma** [comment]
> > App crashes right when saving overlay after entering name on version 1.1.0.
> > Device: Nothing Phone 1.
> 
> Same here

Update: This only works if you are rooted now, since the January 2022 patch of android.
