### ISSUE TITLE
App crashes when I try to save an overlay with a custom name

### ISSUE THREAD

**Issue by BlazeCodeDev** [zacharee/FabricateOverlay#3]
It's saving and working when I leave the name box empty, when I fill anything in however it crashes.

I'm using a Pixel 4XL running the Android 12 Beta 5, rooted with Magisk.

This is the logcat message:

`FATAL EXCEPTION: main
Process: tk.zwander.fabricateoverlay, PID: 15125
java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at tk.zwander.fabricateoverlay.OverlayAPI.commit(OverlayAPI.kt:415)
	at tk.zwander.fabricateoverlay.OverlayAPI.registerFabricatedOverlay(OverlayAPI.kt:207)
	at tk.zwander.fabricateoverlaysample.ui.pages.CurrentOverlaysListPageKt$CurrentOverlaysListPage$5$1$2$1.invoke(CurrentOverlaysListPage.kt:116)
	at tk.zwander.fabricateoverlaysample.ui.pages.CurrentOverlaysListPageKt$CurrentOverlaysListPage$5$1$2$1.invoke(CurrentOverlaysListPage.kt:115)
	at tk.zwander.fabricateoverlay.OverlayAPI$Companion.getInstance(OverlayAPI.kt:100)
	at tk.zwander.fabricateoverlaysample.ui.pages.CurrentOverlaysListPageKt$CurrentOverlaysListPage$5$1$2.invoke(CurrentOverlaysListPage.kt:115)
	at tk.zwander.fabricateoverlaysample.ui.pages.CurrentOverlaysListPageKt$CurrentOverlaysListPage$5$1$2.invoke(CurrentOverlaysListPage.kt:113)
	at androidx.compose.foundation.ClickableKt$clickable$4$gesture$1$2.invoke-k-4lQ0M(Clickable.kt:137)
	at androidx.compose.foundation.ClickableKt$clickable$4$gesture$1$2.invoke(Clickable.kt:131)
	at androidx.compose.foundation.gestures.TapGestureDetectorKt$detectTapAndPress$2$1$1.invokeSuspend(TapGestureDetector.kt:378)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:178)
	at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:166)
	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:397)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:431)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:420)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:328)
	at androidx.compose.ui.input.pointer.SuspendingPointerInputFilter$PointerEventHandlerCoroutine.offerPointerEvent(SuspendingPointerInputFilter.kt:432)
	at androidx.compose.ui.input.pointer.SuspendingPointerInputFilter.dispatchPointerEvent(SuspendingPointerInputFilter.kt:330)
	at androidx.compose.ui.input.pointer.SuspendingPointerInputFilter.onPointerEvent-H0pRuoY(SuspendingPointerInputFilter.kt:343)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:287)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:275)
	at androidx.compose.ui.input.pointer.NodeParent.dispatchMainEventPass(HitPathTracker.kt:151)
	at androidx.compose.ui.input.pointer.HitPathTracker.dispatchChanges(HitPathTracker.kt:90)
	at androidx.compose.ui.input.pointer.PointerInputEventProcessor.process-gBdvCQM(PointerInputEventProcessor.kt:77)
	at androidx.compose.ui.platform.AndroidComposeView.dispatchTouchEvent(AndroidComposeView.android.kt:860)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:502)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1890)
	at android.app.Dialog.dispatchTouchEvent(Dialog.java:864)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:460)
	at android.view.View.dispatchPointerEvent(View.java:14799)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6344)`

**Comment by BlazeCodeDev** [comment]
I'm trying to modify System-UI and my input is "hide battery estimate". I wanted to attach a video but GitHub keeps telling my that it is too big. If you want to I could find another way to upload it.

**Comment by BlazeCodeDev** [comment]
Thanks! Using underscores is in fact working. Maybe a hint which says not to use spaces would be nice. Thank you very much, it's working now. Great app!
